[Defaults]
output_dir = "out"
workflow = "bagger/config/default_workflow.json"
dart_command = "dart-runner"
overwrite = false
delete = true

[Logging]
log_dir = "logs"
logfile_prefix = "ReBACH-Bagger"

[Wasabi]
name = "***override***"
host = "***override***"
bucket = "***override***"
host_bucket = "***override***"
access_key = "***override***"
secret_key = "***override***"
dart_workflow_hostbucket_override = true

[Metadata]
# https://github.com/UAL-RE/ReBACH/blob/12-merge-rebach-bagger/bagger/README.md#metadata

aptrust-info.Title = { tag_path = "title", strip_html = true }
aptrust-info.Description = { tag_path = "description", strip_html = true }

bag-info.Contact-Name = "ReDATA Administrator"
bag-info.Contact-Email = "redata@arizona.edu"
bag-info.Internal-Sender-Identifier = { tag_path = ["doi"] }
bag-info.License-Name = { tag_path = ["license.name"] }
bag-info.Published-Date = { tag_path = ["published_date"] }
bag-info.External-Identifier = { tag_path = ["id", "#version#", "authors.0.first_name", "authors.0.last_name", "#hash#"] }
